swagger: 2.0  
openapi: 3.0.0
info:
  title: Graph Sentiment Flask API
  description: Flask API for generating graphs based on user data and returning to Node.js API
  version: 1.0.0
servers:
  - url: http://54.165.193.93:5001
    description: Graph Sentiment Flask API Server

paths:
  /get-graph:
    post:
      summary: Get Sentiment Graph Endpoint for User Data
      description: Retrieves user data from the database and generates a graph based on the provided user ID.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
      responses:
        '200':
          description: Success. Returns the HTML representation of the graph.
        '400':
          description: Bad Request. If user_id is missing in the request.
        '404':
          description: Not Found. If no data found for the specified user_id.
        '500':
          description: Internal Server Error. If failed to create the graph.

  /test:
    get:
      summary: Test Endpoint
      description: A test endpoint to verify the availability of the Graph Flask API.
      responses:
        '200':
          description: Success. Returns a test message.
        '500':
          description: Internal Server Error. If failed to process the request.
