from: mhapy.noreply@gmail.com
subject: Concerning Negative Behaviour - mhapy
body: |
  Dear User, 
  
  We hope this message finds you well. We wanted to reach out to you regarding the recent sentiment analysis performed on the text you provided.
  
  You submitted content that was found to be more extreme than the threshold we consider concerning.
  
  This indicates that you might be going through a difficult period.
  
  Your well-being is essential to us, and we want to ensure you have the support you may need during challenging times.
  
  We strongly encourage you to consider seeking assistance or talking to someone who can offer support. Remember, seeking help is a sign of strength, and there are many organizations and individuals available to provide assistance.
  
  Here are a few international helplines and resources that can offer support:
  
  - International Suicide Prevention Hotlines:
    - National Suicide Prevention Lifeline (USA): 1-800-273-8255
    - Samaritans (UK and Ireland): 116 123
    - Lifeline (Australia): 13 11 14
    - International Suicide Hotlines: https://en.wikipedia.org/wiki/List_of_suicide_crisis_lines
  
  - Mental Health Support and Resources:
    - Mind (UK): https://www.mind.org.uk/
    - National Alliance on Mental Illness (NAMI, USA): https://www.nami.org/
    - Beyond Blue (Australia): https://www.beyondblue.org.au/
  
  Remember, these resources are available to provide assistance and guidance, whether it's for mental health support, crisis intervention, or simply someone to talk to in times of distress.
  
  Please prioritize your well-being and reach out for help if you're feeling overwhelmed. You're not alone, and there are people who care about you and are ready to support you through difficult times.
  
  Take care of yourself, and please don't hesitate to seek help.
  
  Best regards,
  mhapy
